# Generated by Django 5.2.6 on 2025-09-16 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_ingredient_alter_dish_ingredient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='ingredient',
            field=models.ManyToManyField(related_name='ingredients', to='service.ingredient'),
        ),
    ]
