# Generated by Django 5.2.6 on 2025-09-16 16:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_alter_dish_ingredient'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='cooks',
            field=models.ManyToManyField(blank=True, related_name='dishes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dish',
            name='ingredient',
            field=models.ManyToManyField(related_name='dishes_with_this_ingredient', to='service.ingredient'),
        ),
    ]
