# Generated by Django 4.1 on 2025-09-16 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_dish_cooks_alter_dish_ingredient'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dish',
            old_name='ingredient',
            new_name='ingredients',
        ),
    ]
