# Generated by Django 4.1 on 2025-09-17 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_rename_ingredient_dish_ingredients'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dish',
            options={'ordering': ('name',)},
        ),
    ]
